

all : PasswordGenerator

PasswordGenerator : PasswordGenerator.class

PasswordGenerator.class : PasswordGenerator.java
	javac PasswordGenerator.java
	
clean : PasswordGenerator.class
		del PasswordGenerator.class